name: scenepr
favicon: null
layout_spectrum: 1
typography_spectrum: 0.23759
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c9c9c9'
    - '#333333'
    - '#626262'
    - '#ca0501'
  brandStrength: 0.3125
  lightness: 0.3125
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
