name: scenepr
favicon: null
layout_spectrum: 0.85352
typography_spectrum: 0.23759
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c9c9c9'
    - '#333333'
    - '#626262'
    - '#ca0501'
  brandStrength: 0.8125
  lightness: 0.3407487557269633
  saturation: 0.622226879466325
  rhythmicContrast: 0.75
purpose: []
